### ISSUE TITLE
Timeout when importing gpx

### ISSUE THREAD

**Issue by pmakowski** [SamR1/FitTrackee#183]
Hi,
for the first time, when I try to import a gpx, I'm getting a `[CRITICAL] WORKER TIMEOUT`
and just after `Worker with pid 2128808 was terminated due to signal 9`
here is the gpx file : [2022-05-08-08-01-05.zip](https://github.com/SamR1/FitTrackee/files/8650508/2022-05-08-08-01-05.zip)
Any clue ?
Thanks

**Comment by SamR1** [comment]
Hi,

I didn't manage to reproduce the error with the same file (with and without docker (locally or on my production instance)).

Do you use docker? 
On the sample files available [here](https://github.com/SamR1/docker-fittrackee), gunicorn timeout is configured to 300s in order to process large files.

Processing gpx files needs some improvements, planned in a next version (this part hasn't really changed since the first versions...).

**Comment by pmakowski** [comment]
Today the import work well.
I don't use docker, I use a systemd unit file as indicated here https://samr1.github.io/FitTrackee/installation.html in "Deployment"

**Comment by SamR1** [comment]
OK, thanks for your feedback.
