### ISSUE TITLE
Unnecessary folder: fittrackee/dist ?

### ISSUE THREAD

**Issue by gorgobacka** [SamR1/FitTrackee#199]
While checking and trying to understand the codebase, I was wondering, if the folder "fittrackee/dist" needs to be checked into git, because it can be created on the fly.

Btw: the Makefile points to `rm -rf dist/` and .gitignore to `/dist` instead of `fittrackee/dist`.

But maybe I get it wrong here and the folder is needed for something specific.

If it's a stupid request, please excuse me and close it. But I'm excited about the project and plan to contribute in the future. Therefore, I'm looking at the codebase at the moment.

**Comment by SamR1** [comment]
Hi,

`fittrackee/dist` contains static assets present in the package available on [PyPI](https://pypi.org/project/fittrackee/). The client part is a single-page application directly served by **Flask**.
`dist` is a temporary directory used to generate the package with **Poetry**.

It's not a common architecture, but for now it eases installation and limits requirements (no javascript tool needed to install **FitTrackee** on production, from PyPI or by cloning the repo). 
Since there is no specific configuration for the client part,  it's not mandatory to build assets for a given configuration.

But there are some disadvantages for development (see the [contribution guide](https://github.com/SamR1/FitTrackee/blob/master/CONTRIBUTING.md)).
Maybe I should organize the project differently.

And no problem if you have other questions :). You can also reach me on Matrix: [#fittrackee:matrix.org](https://matrix.to/#/#fittrackee:matrix.org)

**Comment by gorgobacka** [comment]
Ok. Thanks for your explanations. Then it makes den sense to keep the folder.
