### ISSUE TITLE
Feature request: "Equipment" that can be associated with workouts

### ISSUE THREAD

**Issue by jat255** [SamR1/FitTrackee#259]
Some proprietary tools have a concept of "gear" or "equipment" that gets saved alongside a workout:

![image](https://user-images.githubusercontent.com/1278301/200064422-e7832bae-1e55-4d66-93f4-a21f3b351ad0.png)

The nice feature with this is it allows you to keep track of how many miles, minutes, etc. you have put on a piece of equipment (useful for runners that swap out shoes every X miles or something). A similar feature in FitTrackee could be nice to have.

Implementation wise, it could probably look a lot like how "sports" are currently implemented, with a new DB table for pieces of equipment (each associated with a user), and then at upload time allowing for selecting of one (or more) pieces of associated equipment.

**Comment by jat255** [comment]
I've started working on this in my [`equipment_for_workouts`](https://github.com/jat255/FitTrackee/tree/equipment_for_workouts)

**Comment by SamR1** [comment]
Hi,

I had the same feature in mind (I have 3 bikes) and planned to work on it with workouts improvements (v0.9.x, I am currently working on v0.8.x when I have some free time).

This feature may have some impacts, is it possible to discuss the changes before (to avoid unnecessary work and plan it in a version)? Thanks in advance.

**Comment by SamR1** [comment]
Hi!

Sorry for my late reply and thanks for the details.

The data model is close to what I had in mind.  
Some quick feedback:
- I agree, maybe the `equipements` table should be in `users/models.py` and depends on `profile` scope.
- Equipement type should also be defined (bike, shoes...). And there are translations to handle on front side. When a user adds an equipement, he has to choose a type. For instance, I had in mind this kind of display:
![equipment](https://user-images.githubusercontent.com/3525167/202841335-52710ebd-cc08-457d-a8cf-e2f230eb3bc2.png)
- I try to write tests using TDD as much as possible on latest features (on some old code, the test coverage is not very good, I planned to work on this in v0.9.x with [workout refactoring](https://github.com/SamR1/FitTrackee/issues/194)). Don't hesitate to add tests.

If you have any questions, you can also reach me on matrix: [#fittrackee:matrix.org](https://matrix.to/#/#fittrackee:matrix.org).

As I said below, I'm currently working on social features, that require a lot of changes and also impact workouts (that's why some features and major changes are pending, integrating new features delaying this part).

**Comment by SamR1** [comment]
released in v0.8.0

**Comment by SamR1** [comment]
for information, I made a script to add equipments to existing workouts: https://codeberg.org/SamR1/workouts-equipments-updater
