### ISSUE TITLE
[Question] Update workouts with equipment

### ISSUE THREAD

**Issue by Firesphere** [SamR1/FitTrackee#648]
I couldn't find an open or closed issue.
I've added about 300 workouts to a new instance, before I realised I should've added my equipment first.

Is it possible to batch/bulk edit the workouts to add equipment to it?

I'm happy to do this as SQL commands directly on the PG database, by the way, if I know what the SQL command should be (roughly)

**Comment by SamR1** [comment]
Hi,

One way to add equipment is to create an [app (client)](https://samr1.github.io/FitTrackee/en/oauth.html) and use the API (to avoid adding invalid equipment and to update equipment totals).  
I made a [script](https://github.com/SamR1/FitTrackee/issues/259#issuecomment-2068213027) to add equipments on my instance depending on some criteria: https://codeberg.org/SamR1/workouts-equipments-updater (I temporarily disabled the API rate limit to avoid errors, since it updates workouts one by one).

In database, equipment association is stored in `workout_equipments` table.
With SQL, you can use a query like this one (to adapt):
```sql
INSERT INTO workout_equipments (workout_id, equipment_id)
SELECT workouts.id,
        (SELECT equipments.id FROM equipments WHERE equipments.label = 'Trek Marlin 7')
FROM   workouts
WHERE  workouts.sport_id = 4  -- Mountain Biking
```
This query will update **all** mountain bike workouts (`sport_id = 4`) with equipment whose label is "Trek Marlin 7". 
After executing the query, you have to refresh equipment totals:
![image](https://github.com/user-attachments/assets/377c6ab6-acf5-4781-b157-08ed3dc50bdd)

(don't forget to backup the database before)

**Comment by Firesphere** [comment]
Awesome, thanks!

**Comment by SamR1** [comment]
feel free to reopen the issue if you have any further questions.
