### ISSUE TITLE
Fails to start after make rebuild

### ISSUE THREAD

**Issue by sgofferj** [SamR1/FitTrackee#79]
I was on some older 0.4 version and did a `make rebuild`. The container build went through without error but the new container fails to start. The only error message is `fittrackee exited with code 3`. Please advise.

**Comment by SamR1** [comment]
commit with fix: https://github.com/SamR1/FitTrackee/commit/25bdb215cbdd26ce6d392467f34cf143f6cf0ff0

TODO: 
- [ ] pin SQLAlchemy version

**Comment by sgofferj** [comment]
I just noticed that I opened the issue in the wrong repo. I meant to open it in https://github.com/SamR1/docker-fittrackee

Anyways, I deleted the container, modified the Dockerfile, rebuilt the container but I still have the same problem. I'll wait for the weekend release then.

**Comment by SamR1** [comment]
No problem, I moved issue in this repo, since it seems to concern FitTrackee startup. I reproduced the error with a fresh install from pip (with and without docker).

Installing SQLAlchemy 1.4.7 fixes FitTrackee startup in both cases.

Maybe there is another problem that I have not reproduced yet. If it persists after the next release, don't hesitate to open an issue in [SamR1/docker-fittrackee](https://github.com/SamR1/docker-fittrackee).
