### ISSUE TITLE
Add ascent and descent parameters in workout import without GPX file 

### ISSUE THREAD

**Issue by paf38** [SamR1/FitTrackee#92]

**Comment by intrigeri** [comment]
I'll add my user story that could be improved with this feature.

I'm new to tracking my sport activities. I have a pile of GPX tracks generated in the past for routing purposes (using bikerouter & friends). To evaluate FitTrackee, the easier it is to import as much as possible from historical data, the better for me.

Now, FitTrackee seems unable to import a GPX without timing information. Fair enough, I can "import without GPX file" and manually input the data. But then I would like to input *all* the data I have, including ascent & descent, otherwise the corresponding stats and records are meaningless.

I understand this is probably a corner case and probably far from the top of the list.

Thanks for considering, and thanks for FitTrackee.

**Comment by SamR1** [comment]
Hi,

I undestand.
I planned to work on workouts improvements in v0.9, but I'll look if I can add ascent/descent for workouts without a gpx file before the rewrite.

**Comment by SamR1** [comment]
released in v0.7.10

**Comment by intrigeri** [comment]
Thanks a lot!
