### ISSUE TITLE
GPX file add fails

### ISSUE THREAD

**Issue by Fmstrat** [SamR1/FitTrackee#96]
An error is received when trying to upload a GPX file of `error during gpx file parsing`. There is nothing showing up in the logs to identify why this would occur. Attached is a sample GPX file that causes the error (renamed TXT to allow upload). This may be because the GPX does not contain time information? It was created using https://gpx.studio

[Camp Saratoga Loop.txt](https://github.com/SamR1/FitTrackee/files/7332615/Camp.Saratoga.Loop.txt)
.

**Comment by SamR1** [comment]
Hi,

Yes, time is missing, this information is needed in order to calculate speed.
You can add it with gpx.studio (with a start time and an average pace):

![Screenshot 2021-10-13 at 08-21-07 gpx studio — the online GPX file editor](https://user-images.githubusercontent.com/3525167/137078074-7a744524-2067-46e0-97ad-f208d38738df.png)

Then the gpx file can be imported.

**Comment by Fmstrat** [comment]
@SamR1 Thanks. Would there be any objections to a PR to add this in if I did it? I'm also thinking of adding some features like a display card for elevation, imperial units, and a map showing all activities.

**Comment by Fmstrat** [comment]
@SamR1 What kind of timeframe on the new UI? Would hate to do things to have you change them up. Is there a beta branch?

Primarily I'm looking for a view that shows all activities on one giant map, with an icon that you can hover over to see the activity.

For the time inserts, the `gpx.studio` times didn't work out well, they played havok on the average speed calculations. I threw this together and it seems to work nicely: https://github.com/Fmstrat/gpx-time. I set it up to also potentially add in "fake" points if a GPX is getting calculated on lack of points, but this didn't seem to be needed for your tool.
